# Generated by Django 4.2.7 on 2026-04-04 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_text', models.TextField(help_text='The message text that triggered emergency detection')),
                ('keywords_found', models.JSONField(default=list, help_text='List of emergency keywords detected in the message')),
                ('severity', models.CharField(choices=[('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='moderate', max_length=10)),
                ('source', models.CharField(choices=[('chat', 'Chat Message'), ('chatbot', 'AI Chatbot'), ('mood_note', 'Mood Note')], default='chat', max_length=20)),
                ('alert_triggered', models.BooleanField(default=True, help_text='Whether the emergency resources were shown to the user')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User whose message triggered the emergency detection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emergency_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
