# Generated by Django 4.2.7 on 2026-04-04 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('happy', 'Happy 😊'), ('calm', 'Calm 😌'), ('anxious', 'Anxious 😰'), ('sad', 'Sad 😢'), ('angry', 'Angry 😠'), ('hopeful', 'Hopeful 🌟'), ('numb', 'Numb 😶'), ('overwhelmed', 'Overwhelmed 😩')], help_text="User's mood selection", max_length=20)),
                ('note', models.TextField(blank=True, help_text='Optional note about the mood (max 500 chars)', max_length=500, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='The date this mood was recorded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The anonymous user this mood belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mood_entries',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
